repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: flake8
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v1.6.1
    hooks:
    - id: pretty-format-java
      args: [--autofix]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --line-length=79
  - repo: https://gitlab.com/devopshq/gitlab-ci-linter
    rev: v1.0.3
    hooks:
      - id: gitlab-ci-linter
        args:
          - --server=https://git.grammatech.com
          - --filename=.ci/gitlab-ci.yml
